import{S as d,i as u}from"./assets/vendor-BrddEoy-.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="46140865-1cf24fb63bb06dafc67be25f6";function p(i){return new Promise((a,s)=>{let e=`https://pixabay.com/api/?${new URLSearchParams({key:m,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;fetch(e).then(t=>t.json()).then(t=>{a(t)}).catch(t=>{s(t)})})}const c=new d(".gallery-container a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery-container");function h(i){const a=i.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
                <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" width=""/>
                <div class="small-container">
                <div class="text-div"><p class="image-info-title">Likes</p><span class="image-info-value">${s.likes}</span></div>
                <div class="text-div"><p class="image-info-title">Views</p><span class="image-info-value">${s.views}</span></div>
                <div class="text-div"><p class="image-info-title">Comments</p><span class="image-info-value">${s.comments}</span></div>
                <div class="text-div"><p class="image-info-title">Downloads</p><span class="image-info-value">${s.downloads}</span></div>
                </div>
            </a>
        </li>`).join("");f.innerHTML=a,c.refresh()}function g(){f.innerHTML="",c.refresh()}const n=document.querySelector("form"),l=document.querySelector(".loader-container");n.addEventListener("submit",i=>{i.preventDefault();const a=n.elements.search.value.trim();a!==""&&(l.style.display="flex",g(),p(a).then(s=>{const r=s.hits;console.log(r),r.length===0?u.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):h(r)}).catch(s=>{console.log(s)}).finally(()=>{l.style.display="none"}))});
//# sourceMappingURL=index.js.map
